[Mon Sep 11 16:50:50.302767 2017] [:error] [pid 12353] [client 127.0.0.1:38760] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/boards-api/var/cache/prod)\n' in /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676\nStack trace:\n#0 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/boards-api/web/app.php(19): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676
[Mon Sep 11 16:50:52.233900 2017] [:error] [pid 12354] [client 127.0.0.1:38771] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/boards-api/var/cache/prod)\n' in /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676\nStack trace:\n#0 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/boards-api/web/app.php(19): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676
[Mon Sep 11 16:51:14.246720 2017] [:error] [pid 12356] [client 127.0.0.1:38867] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/boards-api/var/logs)\n' in /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:679\nStack trace:\n#0 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/boards-api/web/app.php(19): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 679
[Mon Sep 11 16:51:16.384931 2017] [:error] [pid 12356] [client 127.0.0.1:38867] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/boards-api/var/logs)\n' in /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:679\nStack trace:\n#0 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/boards-api/web/app.php(19): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 679
[Mon Sep 11 16:51:16.739027 2017] [:error] [pid 12356] [client 127.0.0.1:38867] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/boards-api/var/logs)\n' in /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:679\nStack trace:\n#0 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(576): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(119): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /var/www/boards-api/web/app.php(19): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}\n  thrown in /var/www/boards-api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 679
